name: Selenium BDD Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Reqnroll tag to run'
        required: true
        default: 'smoke'
        options:
         - smoke
         - regression

      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
         - chrome
         - edge
         - firefox

      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'STAGE'
        type: choice
        options:
         - STAGE
         - PROD

jobs:
  test:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}

    env:
     BROWSER: ${{ github.event.inputs.browser }}
     ENVIRONMENT: ${{ github.event.inputs.environment }}
     SAUCEDEMO_USER_NAME: ${{ secrets.SAUCEDEMO_USER_NAME }}
     SAUCEDEMO_USER_PWD: ${{ secrets.SAUCEDEMO_USER_PWD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Send email notification
      if: always()   # or: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Selenium BDD Tests - ${{ job.status }}
        to: vijeth2011@gmail.com
        from: GitHub Actions <actions@example.com>
        body: |
          Workflow: Selenium BDD Tests
          Status: ${{ job.status }}
          Browser: ${{ github.event.inputs.browser }}
          Environment: ${{ github.event.inputs.environment }}
          Tag: ${{ github.event.inputs.tag }}
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal --filter Category=${{ github.event.inputs.tag }} -p:Browser=${{ github.event.inputs.browser }} -p:Environment=${{ github.event.inputs.environment }}

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ExtentTestResults
        path: ${{ github.workspace }}\Reports\ReqnrollReport\
